behaviors:
  BoundarySequence:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    
    behavioral_cloning:
      demo_path: C:/Users/flyin/github/ml-agents/Project/Assets/ML-Agents/Scenes/Demonstrations/agentdemo.demo
      strength: 0.5
      steps: 150000
    
    
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        encoding_size: 256
        learning_rate: 0.0003
      gail:
        strength: 0.5
        demo_path: C:/Users/flyin/github/ml-agents/Project/Assets/ML-Agents/Scenes/Demonstrations/agentdemo.demo
        
    max_steps: 2000000
    time_horizon: 1000
    summary_freq: 10000
    threaded: true